services:
  app:
    image: meteo-app-orchestrator:latest
    ports:
      - "${SPRING_BOOT_PORT}:${SPRING_BOOT_PORT}"
    build:
      context: ./
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      database:
        condition: service_healthy
    develop:
      watch:
        - path: ./src
          action: rebuild
        - path: pom.xml
          action: rebuild
    labels:
      traefik.http.routers.backend.rule: Host(`localhost`) && PathPrefix(`/api`)
      traefik.http.routers.backend.middlewares: strip-api
      traefik.http.middlewares.strip-api.stripprefix.prefixes: /api
      traefik.http.services.backend.loadbalancer.server.port: 8081